- alias: 书房窗帘关
  trigger:
    - platform: time
      at: '12:30:00'
    - platform: numeric_state
      entity_id: sensor.shu_fang_liang_du
      above: 200
      for:
        minutes: 10
  condition:
    - condition: numeric_state
      entity_id: sensor.shu_fang_liang_du
      above: 180
    - condition: time
      after: '12:00'
      before: '16:00'
  action:
    - service: cover.close_cover
      entity_id: cover.shu_fang_chuang_lian

- alias: 书房窗帘开
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:30:00'
  condition:
    - condition: state
      entity_id: cover.shu_fang_chuang_lian
      state: closed
    - condition: state
      entity_id: switch.tou_ying_yi
      state: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.shu_fang_chuang_lian
