- alias: 语音播报
  trigger:
    - platform: state
      entity_id: input_text.yu_yin_bo_bao
  action:
    - condition: template
      value_template: '{{ states("input_text.yu_yin_bo_bao") != "unknown" and states("input_text.yu_yin_bo_bao") != "" }}'
    - service: tts.baidu_say
      data_template:
        entity_id: media_player.tian_mao_jing_ling
        message: '{{ states("input_text.yu_yin_bo_bao") }}'

- alias: 开合过道卷帘
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00041c74da
      from: 'off'
      to: 'on'
      for: 
        seconds: 10
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00041c74da
      from: 'on'
      to: 'off'
  action:
    - service_template: 'cover.{% if is_state("binary_sensor.door_window_sensor_158d00041c74da", "off") %}open{% else %}close{% endif %}_cover'
      entity_id: cover.curtain_158d0003f7951d

